<form action="inscription" method="post">
  <label>Nom</label>
  <input type="text" name="nom">
  <label>Prenom</label>
  <input type="text" name="prenom" >
  <label>Nom du compte</label>
  <input type="text" name="nom_de_compte" >
  <label>Mot de passe</label>
  <input type="password" name="mdp">
  <!--<label>adresse Mail</label>
  <input type="text" name="email">-->
  <label>telephone</label>
  <input type="text" name="telephone">
  <input type="submit" value="s'inscrire">
</form>
